/**
 * Chinese search aliases for GitHub shortcodes.
 * Values are space-separated labels; pinyin is derived at search-index build.
 */
export const EMOJI_ZH_ALIASES: Record<string, string> = {
  'grinning': `嘿嘿 咧嘴笑`,
  'smiley': `笑脸 微笑`,
  'smile': `微笑 笑 开心 高兴`,
  'grin': `咧嘴 嘻嘻`,
  'laughing': `大笑 哈哈`,
  'sweat_smile': `苦笑 尴尬笑`,
  'rofl': `笑翻 打滚笑`,
  'joy': `笑哭 喜极而泣`,
  'slightly_smiling_face': `浅笑 微笑`,
  'upside_down_face': `倒脸 颠倒`,
  'wink': `眨眼 使眼色`,
  'blush': `害羞 脸红`,
  'innocent': `天使 天真`,
  'heart_eyes': `花痴 爱心眼`,
  'kissing_heart': `飞吻 亲亲`,
  'yum': `好吃 美味`,
  'stuck_out_tongue': `吐舌`,
  'stuck_out_tongue_winking_eye': `调皮 吐舌眨眼`,
  'zany_face': `搞怪 疯狂`,
  'money_mouth_face': `发财 钱嘴`,
  'hugs': `拥抱 抱抱`,
  'thinking': `思考 想一想`,
  'zipper_mouth_face': `闭嘴 拉链嘴`,
  'neutral_face': `面无表情 平淡`,
  'expressionless': `无语 呆`,
  'no_mouth': `没嘴`,
  'smirk': `得意 坏笑`,
  'unamused': `无语 不爽`,
  'roll_eyes': `白眼 翻白眼`,
  'grimacing': `龇牙 尴尬`,
  'relieved': `松一口气 释然`,
  'pensive': `沉思 忧伤`,
  'sleepy': `困 想睡`,
  'drooling_face': `流口水`,
  'sleeping': `睡觉 睡着`,
  'mask': `口罩 生病`,
  'face_with_thermometer': `发烧`,
  'nauseated_face': `恶心 想吐`,
  'sneezing_face': `打喷嚏`,
  'hot_face': `热 中暑`,
  'cold_face': `冷 冻僵`,
  'dizzy_face': `晕 头晕`,
  'exploding_head': `爆炸头 震惊`,
  'cowboy_hat_face': `牛仔`,
  'partying_face': `派对 庆祝`,
  'sunglasses': `墨镜 酷`,
  'nerd_face': `书呆子 眼镜`,
  'confused': `困惑 疑惑`,
  'worried': `担心 忧虑`,
  'open_mouth': `吃惊 张嘴`,
  'astonished': `惊讶`,
  'flushed': `脸红 羞`,
  'pleading_face': `求求你 可怜`,
  'frowning_face': `皱眉 不开心`,
  'anguished': `痛苦`,
  'fearful': `害怕`,
  'cold_sweat': `冷汗`,
  'disappointed_relieved': `失望又释然`,
  'cry': `哭 流泪`,
  'sob': `大哭 痛哭`,
  'scream': `尖叫 吓死`,
  'confounded': `纠结`,
  'persevere': `坚持 咬牙`,
  'disappointed': `失望`,
  'sweat': `汗 无语汗`,
  'weary': `疲惫 累`,
  'tired_face': `好累`,
  'yawning_face': `打哈欠 困`,
  'triumph': `得意 哼`,
  'rage': `愤怒 怒`,
  'angry': `生气 怒`,
  'smiling_imp': `坏笑恶魔`,
  'imp': `恶魔`,
  'skull': `骷髅 死亡`,
  'ghost': `鬼 幽灵`,
  'alien': `外星人`,
  'robot': `机器人`,
  'poop': `便便 屎`,
  'hankey': `便便 屎`,
  'clown_face': `小丑`,
  'wave': `挥手 你好 再见`,
  'raised_hand': `举手 停`,
  'ok_hand': `好的 没问题`,
  'v': `耶 胜利`,
  'crossed_fingers': `祈祷好运 交叉手指`,
  'love_you_gesture': `爱你`,
  'call_me_hand': `打电话`,
  'point_left': `左边 指左`,
  'point_right': `右边 指右`,
  'point_up_2': `上面 指上`,
  'point_down': `下面 指下`,
  'point_up': `指上 注意`,
  '+1': `赞 好 同意 点赞`,
  'thumbsup': `赞 好 同意 点赞`,
  '-1': `踩 差 反对`,
  'thumbsdown': `踩 差 反对`,
  'fist': `拳头`,
  'facepunch': `出拳 打`,
  'clap': `鼓掌 拍手`,
  'raised_hands': `举双手 万岁`,
  'open_hands': `摊手`,
  'handshake': `握手 合作`,
  'pray': `祈祷 拜托 合十`,
  'muscle': `肌肉 加油`,
  'writing_hand': `写字`,
  'nail_care': `指甲油`,
  'eyes': `眼睛 看`,
  'brain': `大脑 聪明`,
  'baby': `宝宝 婴儿`,
  'man': `男人`,
  'woman': `女人`,
  'bust_in_silhouette': `人 剪影`,
  'busts_in_silhouette': `人们`,
  'technologist': `程序员 码农`,
  'detective': `侦探`,
  'construction_worker': `工人`,
  'superhero': `超人 英雄`,
  'santa': `圣诞老人`,
  'dancer': `跳舞`,
  'running': `跑步`,
  'walking': `走路`,
  'dog': `狗 狗头`,
  'cat': `猫 猫咪`,
  'mouse': `老鼠`,
  'hamster': `仓鼠`,
  'rabbit': `兔子`,
  'fox_face': `狐狸`,
  'bear': `熊`,
  'panda_face': `熊猫`,
  'koala': `考拉`,
  'tiger': `老虎`,
  'lion': `狮子`,
  'cow': `牛`,
  'pig': `猪`,
  'frog': `青蛙`,
  'monkey_face': `猴子`,
  'see_no_evil': `不看 非礼勿视`,
  'hear_no_evil': `不听 非礼勿听`,
  'speak_no_evil': `不说 非礼勿言`,
  'chicken': `鸡`,
  'penguin': `企鹅`,
  'bird': `鸟`,
  'duck': `鸭子`,
  'eagle': `鹰`,
  'owl': `猫头鹰`,
  'bat': `蝙蝠`,
  'wolf': `狼`,
  'horse': `马`,
  'unicorn': `独角兽`,
  'bee': `蜜蜂`,
  'bug': `虫子`,
  'butterfly': `蝴蝶`,
  'snail': `蜗牛`,
  'spider': `蜘蛛`,
  'turtle': `乌龟`,
  'snake': `蛇`,
  'dragon': `龙`,
  'whale': `鲸鱼`,
  'dolphin': `海豚`,
  'fish': `鱼`,
  'octopus': `章鱼`,
  'crab': `螃蟹`,
  'shrimp': `虾`,
  'seedling': `幼苗`,
  'evergreen_tree': `松树`,
  'deciduous_tree': `树`,
  'palm_tree': `棕榈`,
  'cactus': `仙人掌`,
  'herb': `草药 叶子`,
  'four_leaf_clover': `四叶草 幸运`,
  'maple_leaf': `枫叶`,
  'fallen_leaf': `落叶`,
  'leaves': `树叶`,
  'mushroom': `蘑菇`,
  'bouquet': `花束`,
  'cherry_blossom': `樱花`,
  'rose': `玫瑰`,
  'sunflower': `向日葵`,
  'hibiscus': `芙蓉`,
  'tulip': `郁金香`,
  'sunny': `太阳 晴天`,
  'partly_sunny': `多云`,
  'cloud': `云`,
  'rainbow': `彩虹`,
  'umbrella': `雨伞`,
  'zap': `闪电`,
  'snowflake': `雪花`,
  'snowman': `雪人`,
  'fire': `火 火焰 热门`,
  'droplet': `水滴`,
  'ocean': `海浪 海`,
  'star': `星星 星`,
  'star2': `闪亮星`,
  'sparkles': `闪光 星星`,
  'boom': `爆炸 砰`,
  'dizzy': `晕眩`,
  'moon': `月亮`,
  'sun_with_face': `太阳脸`,
  'earth_asia': `地球 亚洲`,
  'earth_americas': `地球 美洲`,
  'earth_africa': `地球 非洲`,
  'apple': `苹果`,
  'green_apple': `青苹果`,
  'tangerine': `橘子`,
  'lemon': `柠檬`,
  'banana': `香蕉`,
  'watermelon': `西瓜`,
  'grapes': `葡萄`,
  'strawberry': `草莓`,
  'peach': `桃子`,
  'cherries': `樱桃`,
  'pineapple': `菠萝`,
  'avocado': `牛油果`,
  'tomato': `番茄 西红柿`,
  'corn': `玉米`,
  'hot_pepper': `辣椒`,
  'bread': `面包`,
  'cheese': `奶酪`,
  'hamburger': `汉堡`,
  'fries': `薯条`,
  'pizza': `披萨`,
  'hotdog': `热狗`,
  'taco': `塔可`,
  'popcorn': `爆米花`,
  'rice': `米饭`,
  'ramen': `拉面`,
  'sushi': `寿司`,
  'dumpling': `饺子`,
  'icecream': `冰淇淋`,
  'doughnut': `甜甜圈`,
  'cookie': `饼干 曲奇`,
  'birthday': `生日蛋糕`,
  'cake': `蛋糕`,
  'chocolate_bar': `巧克力`,
  'candy': `糖果`,
  'honey_pot': `蜂蜜`,
  'coffee': `咖啡`,
  'tea': `茶`,
  'beer': `啤酒`,
  'beers': `干杯 啤酒`,
  'wine_glass': `红酒`,
  'cocktail': `鸡尾酒`,
  'champagne': `香槟`,
  'clinking_glasses': `干杯`,
  'soccer': `足球`,
  'basketball': `篮球`,
  'football': `橄榄球`,
  'baseball': `棒球`,
  'tennis': `网球`,
  'volleyball': `排球`,
  '8ball': `台球`,
  'ping_pong': `乒乓`,
  'badminton': `羽毛球`,
  'goal_net': `球门`,
  'dart': `飞镖 目标`,
  'bowling': `保龄球`,
  'video_game': `游戏 手柄`,
  'game_die': `骰子`,
  'chess_pawn': `棋`,
  'jigsaw': `拼图`,
  'art': `调色板 艺术`,
  'clapper': `场记板 电影`,
  'microphone': `麦克风`,
  'headphones': `耳机`,
  'musical_note': `音符`,
  'notes': `音乐`,
  'guitar': `吉他`,
  'trophy': `奖杯 冠军`,
  'medal_sports': `奖牌`,
  '1st_place_medal': `金牌`,
  '2nd_place_medal': `银牌`,
  '3rd_place_medal': `铜牌`,
  'tada': `庆祝 撒花 恭喜`,
  'confetti_ball': `彩带`,
  'balloon': `气球`,
  'gift': `礼物`,
  'ribbon': `丝带`,
  'fireworks': `烟花`,
  'rocket': `火箭`,
  'airplane': `飞机`,
  'helicopter': `直升机`,
  'ship': `船`,
  'sailboat': `帆船`,
  'car': `汽车`,
  'taxi': `出租车`,
  'bus': `公交`,
  'truck': `卡车`,
  'tractor': `拖拉机`,
  'bike': `自行车`,
  'motorcycle': `摩托`,
  'train': `火车`,
  'bullettrain_side': `高铁`,
  'station': `车站`,
  'traffic_light': `红绿灯`,
  'construction': `施工`,
  'house': `房子 家`,
  'office': `办公楼`,
  'hospital': `医院`,
  'bank': `银行`,
  'school': `学校`,
  'factory': `工厂`,
  'japanese_castle': `日式城堡`,
  'european_castle': `城堡`,
  'statue_of_liberty': `自由女神`,
  'tokyo_tower': `东京塔`,
  'mount_fuji': `富士山`,
  'mountain': `山`,
  'volcano': `火山`,
  'desert_island': `荒岛`,
  'beach_umbrella': `海滩`,
  'tent': `帐篷`,
  'world_map': `地图`,
  'compass': `指南针`,
  'computer': `电脑 笔记本`,
  'desktop_computer': `台式机`,
  'keyboard': `键盘`,
  'computer_mouse': `鼠标`,
  'printer': `打印机`,
  'iphone': `手机`,
  'telephone': `电话`,
  'fax': `传真`,
  'tv': `电视`,
  'camera': `相机`,
  'video_camera': `摄像机`,
  'movie_camera': `电影机`,
  'vhs': `录像带`,
  'mag': `搜索 放大镜`,
  'mag_right': `放大镜`,
  'bulb': `灯泡 想法`,
  'flashlight': `手电筒`,
  'candle': `蜡烛`,
  'battery': `电池`,
  'electric_plug': `插头`,
  'floppy_disk': `软盘`,
  'cd': `光盘`,
  'minidisc': `迷你光盘`,
  'dvd': `dvd`,
  'satellite': `卫星`,
  'hourglass': `沙漏`,
  'hourglass_flowing_sand': `沙漏`,
  'watch': `手表`,
  'alarm_clock': `闹钟`,
  'stopwatch': `秒表`,
  'bell': `铃铛 通知`,
  'no_bell': `静音`,
  'loudspeaker': `喇叭`,
  'mega': `扩音器`,
  'postbox': `邮筒`,
  'email': `邮件`,
  'envelope': `信封`,
  'package': `包裹`,
  'memo': `备忘 笔记`,
  'pencil2': `铅笔`,
  'black_nib': `钢笔`,
  'paperclip': `回形针`,
  'scissors': `剪刀`,
  'straight_ruler': `尺子`,
  'triangular_ruler': `三角尺`,
  'pushpin': `图钉`,
  'round_pushpin': `定位`,
  'bookmark': `书签`,
  'label': `标签`,
  'books': `书 书籍`,
  'book': `打开的书`,
  'closed_book': `书`,
  'green_book': `绿书`,
  'blue_book': `蓝书`,
  'orange_book': `橙书`,
  'notebook': `笔记本`,
  'ledger': `账本`,
  'page_facing_up': `文件`,
  'page_with_curl': `卷页`,
  'scroll': `卷轴`,
  'clipboard': `剪贴板`,
  'calendar': `日历`,
  'date': `日程`,
  'card_index_dividers': `分隔`,
  'file_folder': `文件夹`,
  'open_file_folder': `打开文件夹`,
  'chart_with_upwards_trend': `上涨 趋势`,
  'chart_with_downwards_trend': `下跌`,
  'bar_chart': `柱状图`,
  'abacus': `算盘`,
  'moneybag': `钱袋 钱`,
  'credit_card': `信用卡`,
  'gem': `钻石`,
  'hammer': `锤子`,
  'wrench': `扳手`,
  'nut_and_bolt': `螺丝`,
  'gear': `齿轮 设置`,
  'hammer_and_wrench': `工具`,
  'toolbox': `工具箱`,
  'magnet': `磁铁`,
  'test_tube': `试管`,
  'petri_dish': `培养皿`,
  'dna': `基因`,
  'microscope': `显微镜`,
  'telescope': `望远镜`,
  'pill': `药丸`,
  'syringe': `针筒`,
  'key': `钥匙`,
  'lock': `锁 上锁`,
  'unlock': `解锁`,
  'closed_lock_with_key': `上锁`,
  'shield': `盾牌`,
  'crystal_ball': `水晶球`,
  'broom': `扫帚`,
  'basket': `篮子`,
  'wastebasket': `垃圾桶`,
  'door': `门`,
  'bed': `床`,
  'bathtub': `浴缸`,
  'shopping_cart': `购物车`,
  'crown': `皇冠`,
  'ring': `戒指`,
  'briefcase': `公文包`,
  'heart': `爱心 喜欢 心`,
  'orange_heart': `橙心`,
  'yellow_heart': `黄心`,
  'green_heart': `绿心`,
  'blue_heart': `蓝心`,
  'purple_heart': `紫心`,
  'black_heart': `黑心`,
  'white_heart': `白心`,
  'broken_heart': `心碎`,
  'two_hearts': `两颗心`,
  'sparkling_heart': `闪亮爱心`,
  'heartpulse': `心跳`,
  'cupid': `丘比特`,
  'gift_heart': `心形礼物`,
  '100': `一百分 满分`,
  'anger': `怒 青筋`,
  'speech_balloon': `对话`,
  'thought_balloon': `思考泡泡`,
  'zzz': `睡觉 zzz`,
  'warning': `警告`,
  'no_entry': `禁止通行`,
  'no_entry_sign': `禁止`,
  'bangbang': `双叹号`,
  'interrobang': `叹问号`,
  'question': `问号`,
  'grey_question': `问号`,
  'exclamation': `感叹号`,
  'grey_exclamation': `感叹号`,
  'white_check_mark': `完成 对勾`,
  'heavy_check_mark': `对勾`,
  'ballot_box_with_check': `勾选`,
  'x': `叉 错误`,
  'negative_squared_cross_mark': `叉`,
  'heavy_plus_sign': `加`,
  'heavy_minus_sign': `减`,
  'heavy_multiplication_x': `乘`,
  'heavy_division_sign': `除`,
  'infinity': `无限`,
  'recycle': `回收`,
  'arrow_right': `向右`,
  'arrow_left': `向左`,
  'arrow_up': `向上`,
  'arrow_down': `向下`,
  'arrow_right_hook': `右转`,
  'leftwards_arrow_with_hook': `返回`,
  'arrows_counterclockwise': `刷新`,
  'repeat': `重复`,
  'back': `返回`,
  'soon': `马上`,
  'top': `顶部`,
  'new': `新`,
  'free': `免费`,
  'ok': `好的 ok`,
  'sos': `求救`,
  'up': `上升`,
  'cool': `酷`,
  'id': `证件`,
  'vs': `对决`,
  'abc': `字母`,
  '1234': `数字`,
  'symbols': `符号`,
  'copyright': `版权`,
  'registered': `注册商标`,
  'tm': `商标`,
  'radioactive': `辐射`,
  'biohazard': `生化`,
  'atom_symbol': `原子`,
  'wheelchair': `无障碍`,
  'no_smoking': `禁止吸烟`,
  'put_litter_in_its_place': `垃圾入箱`,
  'potable_water': `饮用水`,
  'wc': `厕所`,
  'red_circle': `红圈`,
  'orange_circle': `橙圈`,
  'yellow_circle': `黄圈`,
  'green_circle': `绿圈`,
  'large_blue_circle': `蓝圈`,
  'purple_circle': `紫圈`,
  'black_circle': `黑圈`,
  'white_circle': `白圈`,
  'red_square': `红方`,
  'orange_square': `橙方`,
  'yellow_square': `黄方`,
  'green_square': `绿方`,
  'blue_square': `蓝方`,
  'purple_square': `紫方`,
  'black_large_square': `黑方`,
  'white_large_square': `白方`,
  'small_blue_diamond': `蓝菱`,
  'small_orange_diamond': `橙菱`,
  'large_blue_diamond': `大蓝菱`,
  'large_orange_diamond': `大橙菱`,
  'diamond_shape_with_a_dot_inside': `菱形`,
  'triangular_flag_on_post': `三角旗`,
  'checkered_flag': `终点旗`,
  'crossed_flags': `交叉旗`,
  'black_flag': `黑旗`,
  'white_flag': `白旗`,
  'rainbow_flag': `彩虹旗`,
}
