/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BUILTIN_QUICK_COMMAND_IDS: typeof import('./src/stores/quickCommands').BUILTIN_QUICK_COMMAND_IDS
  const EffectScope: typeof import('vue').EffectScope
  const SLASH_BASIC_BLOCK_IDS: typeof import('./src/composables/slashCommands').SLASH_BASIC_BLOCK_IDS
  const SLASH_BASIC_FORMAT_IDS: typeof import('./src/composables/slashCommands').SLASH_BASIC_FORMAT_IDS
  const SLASH_EDIT_DOC_IDS: typeof import('./src/composables/slashCommands').SLASH_EDIT_DOC_IDS
  const SLASH_HEADING_IDS: typeof import('./src/composables/slashCommands').SLASH_HEADING_IDS
  const UPLOAD_HOST_VALUES: typeof import('./src/composables/useLocalizedUploadHosts').UPLOAD_HOST_VALUES
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const aiConfig: typeof import('./src/stores/aiConfig').default
  const aiImageConfig: typeof import('./src/stores/aiImageConfig').default
  const asyncComputed: typeof import('@vueuse/core').asyncComputed
  const autoResetRef: typeof import('@vueuse/shared').autoResetRef
  const buildAIHeaders: typeof import('./src/composables/useAIFetch').buildAIHeaders
  const buildPostTree: typeof import('./src/composables/usePostTree').buildPostTree
  const buildSlashCommands: typeof import('./src/composables/slashCommands').buildSlashCommands
  const canDiscoverAIModels: typeof import('./src/composables/useDiscoverAIModels').canDiscoverAIModels
  const completeInitialPreviewBoot: typeof import('./src/composables/useInitialPreviewBoot').completeInitialPreviewBoot
  const computed: typeof import('vue').computed
  const computedAsync: typeof import('@vueuse/core').computedAsync
  const computedEager: typeof import('@vueuse/shared').computedEager
  const computedInject: typeof import('@vueuse/core').computedInject
  const computedWithControl: typeof import('@vueuse/shared').computedWithControl
  const controlledComputed: typeof import('@vueuse/shared').controlledComputed
  const controlledRef: typeof import('@vueuse/shared').controlledRef
  const createApp: typeof import('vue').createApp
  const createComponentCompletionExtension: typeof import('./src/composables/useComponentCompletion').createComponentCompletionExtension
  const createComponentCompletionSource: typeof import('./src/composables/useComponentCompletion').createComponentCompletionSource
  const createDisposableDirective: typeof import('@vueuse/shared').createDisposableDirective
  const createEventHook: typeof import('@vueuse/shared').createEventHook
  const createGlobalState: typeof import('@vueuse/shared').createGlobalState
  const createInjectionState: typeof import('@vueuse/shared').createInjectionState
  const createLocalizedAIServiceOptions: typeof import('./src/composables/useLocalizedAIServices').createLocalizedAIServiceOptions
  const createLocalizedBuiltinComponents: typeof import('./src/composables/useLocalizedBuiltinComponents').createLocalizedBuiltinComponents
  const createLocalizedStyleOptions: typeof import('./src/composables/useLocalizedStyleOptions').createLocalizedStyleOptions
  const createLocalizedUploadHostOptions: typeof import('./src/composables/useLocalizedUploadHosts').createLocalizedUploadHostOptions
  const createPinia: typeof import('pinia').createPinia
  const createReactiveFn: typeof import('@vueuse/shared').createReactiveFn
  const createRef: typeof import('@vueuse/shared').createRef
  const createReusableTemplate: typeof import('@vueuse/core').createReusableTemplate
  const createSharedComposable: typeof import('@vueuse/shared').createSharedComposable
  const createTemplatePromise: typeof import('@vueuse/core').createTemplatePromise
  const createUnrefFn: typeof import('@vueuse/core').createUnrefFn
  const customRef: typeof import('vue').customRef
  const debouncedRef: typeof import('@vueuse/shared').debouncedRef
  const debouncedWatch: typeof import('@vueuse/shared').debouncedWatch
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const eagerComputed: typeof import('@vueuse/shared').eagerComputed
  const effectScope: typeof import('vue').effectScope
  const extendRef: typeof import('@vueuse/shared').extendRef
  const filterFlatPosts: typeof import('./src/composables/usePostTree').filterFlatPosts
  const flattenPostTree: typeof import('./src/composables/usePostTree').flattenPostTree
  const getAIImageServiceLabel: typeof import('./src/composables/useLocalizedAIServices').getAIImageServiceLabel
  const getAIServiceLabel: typeof import('./src/composables/useLocalizedAIServices').getAIServiceLabel
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getThemeLabel: typeof import('./src/composables/useLocalizedStyleOptions').getThemeLabel
  const getUploadHostLabel: typeof import('./src/composables/useLocalizedUploadHosts').getUploadHostLabel
  const h: typeof import('vue').h
  const ignorableWatch: typeof import('@vueuse/shared').ignorableWatch
  const imageUploadCacheKey: typeof import('./src/composables/useImageUploader').imageUploadCacheKey
  const inject: typeof import('vue').inject
  const injectLocal: typeof import('@vueuse/shared').injectLocal
  const isBuiltinQuickCommand: typeof import('./src/stores/quickCommands').isBuiltinQuickCommand
  const isDefined: typeof import('@vueuse/shared').isDefined
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const makeDestructurable: typeof import('@vueuse/shared').makeDestructurable
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const mergeLocalizedComponents: typeof import('./src/composables/useLocalizedBuiltinComponents').mergeLocalizedComponents
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onClickOutside: typeof import('@vueuse/core').onClickOutside
  const onDeactivated: typeof import('vue').onDeactivated
  const onElementRemoval: typeof import('@vueuse/core').onElementRemoval
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onKeyStroke: typeof import('@vueuse/core').onKeyStroke
  const onLongPress: typeof import('@vueuse/core').onLongPress
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onStartTyping: typeof import('@vueuse/core').onStartTyping
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const pausableWatch: typeof import('@vueuse/shared').pausableWatch
  const postSignature: typeof import('./src/stores/post').postSignature
  const provide: typeof import('vue').provide
  const provideLocal: typeof import('@vueuse/shared').provideLocal
  const reactify: typeof import('@vueuse/shared').reactify
  const reactifyObject: typeof import('@vueuse/shared').reactifyObject
  const reactive: typeof import('vue').reactive
  const reactiveComputed: typeof import('@vueuse/shared').reactiveComputed
  const reactiveOmit: typeof import('@vueuse/shared').reactiveOmit
  const reactivePick: typeof import('@vueuse/shared').reactivePick
  const readAIJSONResponse: typeof import('./src/composables/useAIFetch').readAIJSONResponse
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const refAutoReset: typeof import('@vueuse/shared').refAutoReset
  const refDebounced: typeof import('@vueuse/shared').refDebounced
  const refDefault: typeof import('@vueuse/shared').refDefault
  const refManualReset: typeof import('@vueuse/shared').refManualReset
  const refThrottled: typeof import('@vueuse/shared').refThrottled
  const refWithControl: typeof import('@vueuse/shared').refWithControl
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveEndpointUrl: typeof import('./src/composables/useAIFetch').resolveEndpointUrl
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const syncRef: typeof import('@vueuse/shared').syncRef
  const syncRefs: typeof import('@vueuse/shared').syncRefs
  const templateRef: typeof import('@vueuse/core').templateRef
  const throttledRef: typeof import('@vueuse/shared').throttledRef
  const throttledWatch: typeof import('@vueuse/shared').throttledWatch
  const toRaw: typeof import('vue').toRaw
  const toReactive: typeof import('@vueuse/shared').toReactive
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toast: typeof import('./src/lib/toast/index').toast
  const triggerRef: typeof import('vue').triggerRef
  const tryOnBeforeMount: typeof import('@vueuse/shared').tryOnBeforeMount
  const tryOnBeforeUnmount: typeof import('@vueuse/shared').tryOnBeforeUnmount
  const tryOnMounted: typeof import('@vueuse/shared').tryOnMounted
  const tryOnScopeDispose: typeof import('@vueuse/shared').tryOnScopeDispose
  const tryOnUnmounted: typeof import('@vueuse/shared').tryOnUnmounted
  const unref: typeof import('vue').unref
  const unrefElement: typeof import('@vueuse/core').unrefElement
  const until: typeof import('@vueuse/shared').until
  const useAIConfigStore: typeof import('./src/stores/aiConfig').useAIConfigStore
  const useAIFetch: typeof import('./src/composables/useAIFetch').useAIFetch
  const useAIImageConfigStore: typeof import('./src/stores/aiImageConfig').useAIImageConfigStore
  const useAccountSyncBootstrap: typeof import('./src/composables/useAccountSyncBootstrap').useAccountSyncBootstrap
  const useActiveElement: typeof import('@vueuse/core').useActiveElement
  const useAnimate: typeof import('@vueuse/core').useAnimate
  const useArrayDifference: typeof import('@vueuse/shared').useArrayDifference
  const useArrayEvery: typeof import('@vueuse/shared').useArrayEvery
  const useArrayFilter: typeof import('@vueuse/shared').useArrayFilter
  const useArrayFind: typeof import('@vueuse/shared').useArrayFind
  const useArrayFindIndex: typeof import('@vueuse/shared').useArrayFindIndex
  const useArrayFindLast: typeof import('@vueuse/shared').useArrayFindLast
  const useArrayIncludes: typeof import('@vueuse/shared').useArrayIncludes
  const useArrayJoin: typeof import('@vueuse/shared').useArrayJoin
  const useArrayMap: typeof import('@vueuse/shared').useArrayMap
  const useArrayReduce: typeof import('@vueuse/shared').useArrayReduce
  const useArraySome: typeof import('@vueuse/shared').useArraySome
  const useArrayUnique: typeof import('@vueuse/shared').useArrayUnique
  const useAsyncQueue: typeof import('@vueuse/core').useAsyncQueue
  const useAsyncState: typeof import('@vueuse/core').useAsyncState
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useBase64: typeof import('@vueuse/core').useBase64
  const useBattery: typeof import('@vueuse/core').useBattery
  const useBluetooth: typeof import('@vueuse/core').useBluetooth
  const useBreakpoints: typeof import('@vueuse/core').useBreakpoints
  const useBroadcastChannel: typeof import('@vueuse/core').useBroadcastChannel
  const useBrowserLocation: typeof import('@vueuse/core').useBrowserLocation
  const useCached: typeof import('@vueuse/core').useCached
  const useClipboard: typeof import('@vueuse/core').useClipboard
  const useClipboardItems: typeof import('@vueuse/core').useClipboardItems
  const useCloned: typeof import('@vueuse/core').useCloned
  const useColorMode: typeof import('@vueuse/core').useColorMode
  const useCommandPalette: typeof import('./src/composables/useCommandPalette').useCommandPalette
  const useCommandPaletteHotkey: typeof import('./src/composables/useCommandPaletteHotkey').useCommandPaletteHotkey
  const useConfirmDialog: typeof import('@vueuse/core').useConfirmDialog
  const useConfirmStore: typeof import('./src/stores/confirm').useConfirmStore
  const useCountdown: typeof import('@vueuse/core').useCountdown
  const useCounter: typeof import('@vueuse/shared').useCounter
  const useCssEditorStore: typeof import('./src/stores/cssEditor').useCssEditorStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssSupports: typeof import('@vueuse/core').useCssSupports
  const useCssVar: typeof import('@vueuse/core').useCssVar
  const useCssVars: typeof import('vue').useCssVars
  const useCurrentElement: typeof import('@vueuse/core').useCurrentElement
  const useCursorSync: typeof import('./src/composables/useCursorSync').useCursorSync
  const useCustomComponentStore: typeof import('./src/stores/customComponent').useCustomComponentStore
  const useCycleList: typeof import('@vueuse/core').useCycleList
  const useDark: typeof import('@vueuse/core').useDark
  const useDateFormat: typeof import('@vueuse/shared').useDateFormat
  const useDebounce: typeof import('@vueuse/shared').useDebounce
  const useDebounceFn: typeof import('@vueuse/shared').useDebounceFn
  const useDebouncedRefHistory: typeof import('@vueuse/core').useDebouncedRefHistory
  const useDeepLinkImport: typeof import('./src/composables/useDeepLinkImport').useDeepLinkImport
  const useDeviceMotion: typeof import('@vueuse/core').useDeviceMotion
  const useDeviceOrientation: typeof import('@vueuse/core').useDeviceOrientation
  const useDevicePixelRatio: typeof import('@vueuse/core').useDevicePixelRatio
  const useDevicesList: typeof import('@vueuse/core').useDevicesList
  const useDiscoverAIModels: typeof import('./src/composables/useDiscoverAIModels').useDiscoverAIModels
  const useDisplayMedia: typeof import('@vueuse/core').useDisplayMedia
  const useDocumentVisibility: typeof import('@vueuse/core').useDocumentVisibility
  const useDraggable: typeof import('@vueuse/core').useDraggable
  const useDropZone: typeof import('@vueuse/core').useDropZone
  const useEditorDocumentActions: typeof import('./src/composables/useEditorDocumentActions').useEditorDocumentActions
  const useEditorFormat: typeof import('./src/composables/useEditorFormat').useEditorFormat
  const useEditorRefresh: typeof import('./src/composables/useEditorRefresh').useEditorRefresh
  const useEditorStore: typeof import('./src/stores/editor').useEditorStore
  const useElementBounding: typeof import('@vueuse/core').useElementBounding
  const useElementByPoint: typeof import('@vueuse/core').useElementByPoint
  const useElementHover: typeof import('@vueuse/core').useElementHover
  const useElementOverflow: typeof import('@vueuse/core').useElementOverflow
  const useElementSize: typeof import('@vueuse/core').useElementSize
  const useElementVisibility: typeof import('@vueuse/core').useElementVisibility
  const useEmojiPackStore: typeof import('./src/stores/emojiPack').useEmojiPackStore
  const useEventBus: typeof import('@vueuse/core').useEventBus
  const useEventListener: typeof import('@vueuse/core').useEventListener
  const useEventSource: typeof import('@vueuse/core').useEventSource
  const useExportStore: typeof import('./src/stores/export').useExportStore
  const useEyeDropper: typeof import('@vueuse/core').useEyeDropper
  const useFavicon: typeof import('@vueuse/core').useFavicon
  const useFetch: typeof import('@vueuse/core').useFetch
  const useFileDialog: typeof import('@vueuse/core').useFileDialog
  const useFileSystemAccess: typeof import('@vueuse/core').useFileSystemAccess
  const useFocus: typeof import('@vueuse/core').useFocus
  const useFocusWithin: typeof import('@vueuse/core').useFocusWithin
  const useFolderFileSync: typeof import('./src/composables/useFolderFileSync').useFolderFileSync
  const useFolderSourceStore: typeof import('./src/stores/folderSource').useFolderSourceStore
  const useFps: typeof import('@vueuse/core').useFps
  const useFullscreen: typeof import('@vueuse/core').useFullscreen
  const useGamepad: typeof import('@vueuse/core').useGamepad
  const useGeolocation: typeof import('@vueuse/core').useGeolocation
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useIdle: typeof import('@vueuse/core').useIdle
  const useImage: typeof import('@vueuse/core').useImage
  const useImageUploader: typeof import('./src/composables/useImageUploader').useImageUploader
  const useInfiniteScroll: typeof import('@vueuse/core').useInfiniteScroll
  const useIntersectionObserver: typeof import('@vueuse/core').useIntersectionObserver
  const useInterval: typeof import('@vueuse/shared').useInterval
  const useIntervalFn: typeof import('@vueuse/shared').useIntervalFn
  const useKeyModifier: typeof import('@vueuse/core').useKeyModifier
  const useLastChanged: typeof import('@vueuse/shared').useLastChanged
  const useLiveAnnouncer: typeof import('@vueuse/core').useLiveAnnouncer
  const useLocalStorage: typeof import('@vueuse/core').useLocalStorage
  const useLocaleStore: typeof import('./src/stores/locale').useLocaleStore
  const useLocalizedAIServiceOptions: typeof import('./src/composables/useLocalizedAIServices').useLocalizedAIServiceOptions
  const useLocalizedAllComponents: typeof import('./src/composables/useLocalizedBuiltinComponents').useLocalizedAllComponents
  const useLocalizedBuiltinComponents: typeof import('./src/composables/useLocalizedBuiltinComponents').useLocalizedBuiltinComponents
  const useLocalizedStyleOptions: typeof import('./src/composables/useLocalizedStyleOptions').useLocalizedStyleOptions
  const useLocalizedUploadHostOptions: typeof import('./src/composables/useLocalizedUploadHosts').useLocalizedUploadHostOptions
  const useMagicKeys: typeof import('@vueuse/core').useMagicKeys
  const useManualRefHistory: typeof import('@vueuse/core').useManualRefHistory
  const useMarketplaceStore: typeof import('./src/stores/marketplace').useMarketplaceStore
  const useMediaControls: typeof import('@vueuse/core').useMediaControls
  const useMediaQuery: typeof import('@vueuse/core').useMediaQuery
  const useMemoize: typeof import('@vueuse/core').useMemoize
  const useMemory: typeof import('@vueuse/core').useMemory
  const useModel: typeof import('vue').useModel
  const useMounted: typeof import('@vueuse/core').useMounted
  const useMouse: typeof import('@vueuse/core').useMouse
  const useMouseInElement: typeof import('@vueuse/core').useMouseInElement
  const useMousePressed: typeof import('@vueuse/core').useMousePressed
  const useMpAccountsStore: typeof import('./src/stores/mpAccounts').useMpAccountsStore
  const useMutationObserver: typeof import('@vueuse/core').useMutationObserver
  const useNavigatorLanguage: typeof import('@vueuse/core').useNavigatorLanguage
  const useNetwork: typeof import('@vueuse/core').useNetwork
  const useNotificationsStore: typeof import('./src/stores/notifications').useNotificationsStore
  const useNow: typeof import('@vueuse/core').useNow
  const useObjectUrl: typeof import('@vueuse/core').useObjectUrl
  const useOffsetPagination: typeof import('@vueuse/core').useOffsetPagination
  const useOnline: typeof import('@vueuse/core').useOnline
  const usePageLeave: typeof import('@vueuse/core').usePageLeave
  const useParallax: typeof import('@vueuse/core').useParallax
  const useParentElement: typeof import('@vueuse/core').useParentElement
  const usePerformanceObserver: typeof import('@vueuse/core').usePerformanceObserver
  const usePermission: typeof import('@vueuse/core').usePermission
  const usePlatformEnv: typeof import('./src/composables/usePlatformEnv').usePlatformEnv
  const usePointer: typeof import('@vueuse/core').usePointer
  const usePointerLock: typeof import('@vueuse/core').usePointerLock
  const usePointerSwipe: typeof import('@vueuse/core').usePointerSwipe
  const usePostStore: typeof import('./src/stores/post').usePostStore
  const usePreferencesHotkey: typeof import('./src/composables/usePreferencesHotkey').usePreferencesHotkey
  const usePreferredColorScheme: typeof import('@vueuse/core').usePreferredColorScheme
  const usePreferredContrast: typeof import('@vueuse/core').usePreferredContrast
  const usePreferredDark: typeof import('@vueuse/core').usePreferredDark
  const usePreferredLanguages: typeof import('@vueuse/core').usePreferredLanguages
  const usePreferredReducedMotion: typeof import('@vueuse/core').usePreferredReducedMotion
  const usePreferredReducedTransparency: typeof import('@vueuse/core').usePreferredReducedTransparency
  const usePrevious: typeof import('@vueuse/core').usePrevious
  const useQuickCommandsStore: typeof import('./src/stores/quickCommands').useQuickCommandsStore
  const useRafFn: typeof import('@vueuse/core').useRafFn
  const useRefHistory: typeof import('@vueuse/core').useRefHistory
  const useRenderStore: typeof import('./src/stores/render').useRenderStore
  const useResizeObserver: typeof import('@vueuse/core').useResizeObserver
  const useSSRWidth: typeof import('@vueuse/core').useSSRWidth
  const useScreenOrientation: typeof import('@vueuse/core').useScreenOrientation
  const useScreenSafeArea: typeof import('@vueuse/core').useScreenSafeArea
  const useScriptTag: typeof import('@vueuse/core').useScriptTag
  const useScroll: typeof import('@vueuse/core').useScroll
  const useScrollLock: typeof import('@vueuse/core').useScrollLock
  const useScrollSync: typeof import('./src/composables/useScrollSync').useScrollSync
  const useSessionStorage: typeof import('@vueuse/core').useSessionStorage
  const useShare: typeof import('@vueuse/core').useShare
  const useSlashCommand: typeof import('./src/composables/useSlashCommand').useSlashCommand
  const useSlashMenuPosition: typeof import('./src/composables/useSlashMenuPosition').useSlashMenuPosition
  const useSlashMenuScrollHint: typeof import('./src/composables/useSlashMenuScrollHint').useSlashMenuScrollHint
  const useSlots: typeof import('vue').useSlots
  const useSorted: typeof import('@vueuse/core').useSorted
  const useSpeechRecognition: typeof import('@vueuse/core').useSpeechRecognition
  const useSpeechSynthesis: typeof import('@vueuse/core').useSpeechSynthesis
  const useStepper: typeof import('@vueuse/core').useStepper
  const useStorage: typeof import('@vueuse/core').useStorage
  const useStorageAsync: typeof import('@vueuse/core').useStorageAsync
  const useStyleTag: typeof import('@vueuse/core').useStyleTag
  const useSupported: typeof import('@vueuse/core').useSupported
  const useSwipe: typeof import('@vueuse/core').useSwipe
  const useSyncFooterMeta: typeof import('./src/composables/useSyncStatusMeta').useSyncFooterMeta
  const useSyncStatusMeta: typeof import('./src/composables/useSyncStatusMeta').useSyncStatusMeta
  const useSyncStore: typeof import('./src/stores/sync').useSyncStore
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTemplateRefsList: typeof import('@vueuse/core').useTemplateRefsList
  const useTemplateStore: typeof import('./src/stores/template').useTemplateStore
  const useTemporalNow: typeof import('@vueuse/core').useTemporalNow
  const useTextDirection: typeof import('@vueuse/core').useTextDirection
  const useTextSelection: typeof import('@vueuse/core').useTextSelection
  const useTextareaAutosize: typeof import('@vueuse/core').useTextareaAutosize
  const useThemeStore: typeof import('./src/stores/theme').useThemeStore
  const useThrottle: typeof import('@vueuse/shared').useThrottle
  const useThrottleFn: typeof import('@vueuse/shared').useThrottleFn
  const useThrottledRefHistory: typeof import('@vueuse/core').useThrottledRefHistory
  const useTimeAgo: typeof import('@vueuse/core').useTimeAgo
  const useTimeAgoIntl: typeof import('@vueuse/core').useTimeAgoIntl
  const useTimeout: typeof import('@vueuse/shared').useTimeout
  const useTimeoutFn: typeof import('@vueuse/shared').useTimeoutFn
  const useTimeoutPoll: typeof import('@vueuse/core').useTimeoutPoll
  const useTimestamp: typeof import('@vueuse/core').useTimestamp
  const useTitle: typeof import('@vueuse/core').useTitle
  const useToNumber: typeof import('@vueuse/shared').useToNumber
  const useToString: typeof import('@vueuse/shared').useToString
  const useToggle: typeof import('@vueuse/shared').useToggle
  const useTransition: typeof import('@vueuse/core').useTransition
  const useUIStore: typeof import('./src/stores/ui').useUIStore
  const useUrlSearchParams: typeof import('@vueuse/core').useUrlSearchParams
  const useUserMedia: typeof import('@vueuse/core').useUserMedia
  const useVModel: typeof import('@vueuse/core').useVModel
  const useVModels: typeof import('@vueuse/core').useVModels
  const useVibrate: typeof import('@vueuse/core').useVibrate
  const useVirtualList: typeof import('@vueuse/core').useVirtualList
  const useWakeLock: typeof import('@vueuse/core').useWakeLock
  const useWebMCP: typeof import('@vueuse/core').useWebMCP
  const useWebNotification: typeof import('@vueuse/core').useWebNotification
  const useWebSocket: typeof import('@vueuse/core').useWebSocket
  const useWebWorker: typeof import('@vueuse/core').useWebWorker
  const useWebWorkerFn: typeof import('@vueuse/core').useWebWorkerFn
  const useWindowFocus: typeof import('@vueuse/core').useWindowFocus
  const useWindowScroll: typeof import('@vueuse/core').useWindowScroll
  const useWindowSize: typeof import('@vueuse/core').useWindowSize
  const watch: typeof import('vue').watch
  const watchArray: typeof import('@vueuse/shared').watchArray
  const watchAtMost: typeof import('@vueuse/shared').watchAtMost
  const watchDebounced: typeof import('@vueuse/shared').watchDebounced
  const watchDeep: typeof import('@vueuse/shared').watchDeep
  const watchEffect: typeof import('vue').watchEffect
  const watchIgnorable: typeof import('@vueuse/shared').watchIgnorable
  const watchImmediate: typeof import('@vueuse/shared').watchImmediate
  const watchOnce: typeof import('@vueuse/shared').watchOnce
  const watchPausable: typeof import('@vueuse/shared').watchPausable
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const watchThrottled: typeof import('@vueuse/shared').watchThrottled
  const watchTriggerable: typeof import('@vueuse/shared').watchTriggerable
  const watchWithFilter: typeof import('@vueuse/shared').watchWithFilter
  const whenever: typeof import('@vueuse/shared').whenever
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CssContentConfig } from './src/stores/cssEditor'
  import('./src/stores/cssEditor')
  // @ts-ignore
  export type { FileSystemNode } from './src/stores/folderSource'
  import('./src/stores/folderSource')
  // @ts-ignore
  export type { MpAccount } from './src/stores/mpAccounts'
  import('./src/stores/mpAccounts')
  // @ts-ignore
  export type { Post } from './src/stores/post'
  import('./src/stores/post')
  // @ts-ignore
  export type { QuickCommandPersisted, QuickCommandRuntime } from './src/stores/quickCommands'
  import('./src/stores/quickCommands')
  // @ts-ignore
  export type { RenderOptions } from './src/stores/render'
  import('./src/stores/render')
  // @ts-ignore
  export type { SyncStatus } from './src/stores/sync'
  import('./src/stores/sync')
  // @ts-ignore
  export type { SlashCommandGroup, SlashCommandItem } from './src/composables/slashCommands'
  import('./src/composables/slashCommands')
  // @ts-ignore
  export type { SSECallbacks } from './src/composables/useAIFetch'
  import('./src/composables/useAIFetch')
  // @ts-ignore
  export type { PaletteCommand } from './src/composables/useCommandPalette'
  import('./src/composables/useCommandPalette')
  // @ts-ignore
  export type { UploadHostValue } from './src/composables/useLocalizedUploadHosts'
  import('./src/composables/useLocalizedUploadHosts')
  // @ts-ignore
  export type { PostTreeInput, FlatPostTreeNode } from './src/composables/usePostTree'
  import('./src/composables/usePostTree')
  // @ts-ignore
  export type { SyncUiState, SyncStatusMeta } from './src/composables/useSyncStatusMeta'
  import('./src/composables/useSyncStatusMeta')
}
