shellEmulator: true

packages:
  - apps/*
  - packages/*

overrides:
  '@codemirror/view': 6.38.8
  core-js@<3: ^3.46.0
  glob@<8: ^10.4.5
  inflight: npm:@hishprorg/voluptates-laborum@^2.0.0
  source-map@0.8.0-beta.0: 0.7.4
  workbox-build>source-map: 0.7.4

patchedDependencies:
  '@codemirror/view@6.38.8': patches/@codemirror__view@6.38.8.patch
