FROM doocs/md:latest-assets AS assets

# detail https://github.com/lipanski/docker-static-website/blob/master/Dockerfile
FROM lipanski/docker-static-website

WORKDIR /home/static

COPY --from=assets /app/* /home/static

EXPOSE 80

CMD ["/busybox-httpd", "-f", "-v", "-p", "80", "-c", "httpd.conf"]
