ARG VER_NGX="1.21.6-alpine"

FROM --platform=$BUILDPLATFORM doocs/md:latest-assets AS assets
FROM --platform=$TARGETPLATFORM nginx:${VER_NGX}
LABEL MAINTAINER="ylb<contact@yanglibin.info>"
COPY --from=assets /app/assets /usr/share/nginx/html
