name: Cleanup Cloudflare Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/md'
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install wrangler globally
        run: pnpm add -g wrangler

      - name: Delete preview deployment
        id: delete
        continue-on-error: true
        run: |
          echo "Attempting to delete md-pr-${{ github.event.pull_request.number }}"
          wrangler delete md-pr-${{ github.event.pull_request.number }} --force
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment on PR
        if: steps.delete.outcome == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '🗑️ Cloudflare Workers preview deployment has been cleaned up.'
            });
