name: Cloudflare Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/md'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build for Cloudflare Workers
        run: pnpm web build:h5-netlify
        env:
          CF_WORKERS: 1

      - name: Prepare deployment files
        run: |
          # Copy wrangler config and worker code
          mkdir -p deploy-package
          cp -r apps/web/dist deploy-package/
          cp apps/web/wrangler.jsonc deploy-package/wrangler.jsonc
          cp -r apps/web/worker deploy-package/
          
          # Create a minimal package.json without workspace protocol
          cat > deploy-package/package.json << 'EOF'
          {
            "name": "md-preview",
            "version": "1.0.0",
            "private": true
          }
          EOF

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-dist
          path: deploy-package
          retention-days: 5

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-pr
          path: ./pr-id.txt
